swagger: '2.0'
info:
  description: Automatically produces natural language news reports about comments.
  title: Comment Reporter
  version: 0.0.1
paths:
  /health:
    options:
      description: "Returns the version number of the system as well. A reply indicates the system is healthy."
      responses:
        '200':
          description: OK
    get:
      description: "Returns the version number of the system as well. A reply indicates the system is healthy."
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - version
            properties:
              version:
                type: string
                example: "0.1.0"
  /languages:
    options:
      description: "Describes the available HTTP methods for this end point."
      responses:
        '200':
          description: OK
    get:
      description: Returns a JSON array of language codes supported by the /report endpoint.
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - languages
            properties:
              languages:
                type: array
                items:
                  type: string
                example:
                  - en
                  - fi
  /report:
    options:
      description: "Describes the available HTTP methods for this end point."
      responses:
        '200':
          description: OK
    post:
      description: Generate a report about the input comments. Both language parameters are optional. Leaving out the comment_language field implies the comments are multilingual.
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: parameters
          schema:
            type: object
            required:
              - comments
            properties:
              comments:
                type: array
                items:
                  type: string
                example: "[]"
              output_language:
                type: string
                example: "en"
              comment_language:
                type: string
                example: "hr"
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              language:
                type: string
                example: en
              body:
                type: string
                example: <p>...</p>
        '400':
          description: Missing or invalid inputs